[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # imported but unused error

[tool.ruff]
extend-include = ["*.ipynb"]

[project]
name = "raggler"
version = "0.1.0"
dependencies = [
    "rank_bm25",
]
